//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.RPAActivities.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.RPAActivities.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify text using a model.
        /// </summary>
        public static string Classify_Description {
            get {
                return ResourceManager.GetString("Classify_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify.
        /// </summary>
        public static string Classify_DisplayName {
            get {
                return ResourceManager.GetString("Classify_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id of model group.
        /// </summary>
        public static string Classify_ModelGroup_Description {
            get {
                return ResourceManager.GetString("Classify_ModelGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group.
        /// </summary>
        public static string Classify_ModelGroup_DisplayName {
            get {
                return ResourceManager.GetString("Classify_ModelGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classifications.
        /// </summary>
        public static string Classify_Results_Description {
            get {
                return ResourceManager.GetString("Classify_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string Classify_Results_DisplayName {
            get {
                return ResourceManager.GetString("Classify_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text to be classified.
        /// </summary>
        public static string Classify_Text_Description {
            get {
                return ResourceManager.GetString("Classify_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Classify_Text_DisplayName {
            get {
                return ResourceManager.GetString("Classify_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top class for each prediction.
        /// </summary>
        public static string Classify_TopResults_Description {
            get {
                return ResourceManager.GetString("Classify_TopResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Results.
        /// </summary>
        public static string Classify_TopResults_DisplayName {
            get {
                return ResourceManager.GetString("Classify_TopResults_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction config.
        /// </summary>
        public static string DocumentExtraction_ConfigType_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_ConfigType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configType.
        /// </summary>
        public static string DocumentExtraction_ConfigType_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_ConfigType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts Contents from Documents.
        /// </summary>
        public static string DocumentExtraction_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Extraction.
        /// </summary>
        public static string DocumentExtraction_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document for extraction.
        /// </summary>
        public static string DocumentExtraction_Document_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Document_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        public static string DocumentExtraction_Document_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_Document_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Contents.
        /// </summary>
        public static string DocumentExtraction_Results_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string DocumentExtraction_Results_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract values from text with a model.
        /// </summary>
        public static string ExtractValues_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Values.
        /// </summary>
        public static string ExtractValues_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model group to use.
        /// </summary>
        public static string ExtractValues_ModelGroup_Description {
            get {
                return ResourceManager.GetString("ExtractValues_ModelGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group.
        /// </summary>
        public static string ExtractValues_ModelGroup_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_ModelGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extraction results.
        /// </summary>
        public static string ExtractValues_Results_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string ExtractValues_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text to get extractions from.
        /// </summary>
        public static string ExtractValues_Text_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ExtractValues_Text_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetsModelGroupData.
        /// </summary>
        public static string GetModelGroup_Description {
            get {
                return ResourceManager.GetString("GetModelGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetModelGroup.
        /// </summary>
        public static string GetModelGroup_DisplayName {
            get {
                return ResourceManager.GetString("GetModelGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetModelGroup_ModelGroupData_Description {
            get {
                return ResourceManager.GetString("GetModelGroup_ModelGroupData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group Data.
        /// </summary>
        public static string GetModelGroup_ModelGroupData_DisplayName {
            get {
                return ResourceManager.GetString("GetModelGroup_ModelGroupData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetModelGroup_ModelGroupID_Description {
            get {
                return ResourceManager.GetString("GetModelGroup_ModelGroupID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group ID.
        /// </summary>
        public static string GetModelGroup_ModelGroupID_DisplayName {
            get {
                return ResourceManager.GetString("GetModelGroup_ModelGroupID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico credentials scope.
        /// </summary>
        public static string IndicoIPA_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico IPA.
        /// </summary>
        public static string IndicoIPA_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Host Address.
        /// </summary>
        public static string IndicoIPA_Host_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host.
        /// </summary>
        public static string IndicoIPA_Host_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Token.
        /// </summary>
        public static string IndicoIPA_Token_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string IndicoIPA_Token_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Scope.
        /// </summary>
        public static string IndicoScope_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Scope.
        /// </summary>
        public static string IndicoScope_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indico host url.
        /// </summary>
        public static string IndicoScope_Host_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host.
        /// </summary>
        public static string IndicoScope_Host_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indico token.
        /// </summary>
        public static string IndicoScope_Token_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string IndicoScope_Token_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of datasets.
        /// </summary>
        public static string ListDatasets_Datasets_Description {
            get {
                return ResourceManager.GetString("ListDatasets_Datasets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datasets.
        /// </summary>
        public static string ListDatasets_Datasets_DisplayName {
            get {
                return ResourceManager.GetString("ListDatasets_Datasets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List your datasets.
        /// </summary>
        public static string ListDatasets_Description {
            get {
                return ResourceManager.GetString("ListDatasets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Datasets.
        /// </summary>
        public static string ListDatasets_DisplayName {
            get {
                return ResourceManager.GetString("ListDatasets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of dataset to query.
        /// </summary>
        public static string ListWorkflows_DatasetID_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_DatasetID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatasetID.
        /// </summary>
        public static string ListWorkflows_DatasetID_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_DatasetID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List workflows for a dataset.
        /// </summary>
        public static string ListWorkflows_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListWorkflows.
        /// </summary>
        public static string ListWorkflows_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of workflows.
        /// </summary>
        public static string ListWorkflows_Workflows_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_Workflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string ListWorkflows_Workflows_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_Workflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit files or urls to workflow.
        /// </summary>
        public static string WorkflowSubmission_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowSubmission.
        /// </summary>
        public static string WorkflowSubmission_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths of files to submit.
        /// </summary>
        public static string WorkflowSubmission_FilePaths_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_FilePaths_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePaths.
        /// </summary>
        public static string WorkflowSubmission_FilePaths_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_FilePaths_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of submission ids.
        /// </summary>
        public static string WorkflowSubmission_SubmissionIDs_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_SubmissionIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionIDs.
        /// </summary>
        public static string WorkflowSubmission_SubmissionIDs_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_SubmissionIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls to submit.
        /// </summary>
        public static string WorkflowSubmission_Urls_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Urls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls.
        /// </summary>
        public static string WorkflowSubmission_Urls_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Urls_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of workflow for submission.
        /// </summary>
        public static string WorkflowSubmission_WorkflowID_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_WorkflowID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowID.
        /// </summary>
        public static string WorkflowSubmission_WorkflowID_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_WorkflowID_DisplayName", resourceCulture);
            }
        }
    }
}
