//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.RPAActivities.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.RPAActivities.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue this flow on error.
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue On Error.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction config.
        /// </summary>
        public static string DocumentExtraction_ConfigType_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_ConfigType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigType.
        /// </summary>
        public static string DocumentExtraction_ConfigType_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_ConfigType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts Contents from Documents.
        /// </summary>
        public static string DocumentExtraction_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Extraction.
        /// </summary>
        public static string DocumentExtraction_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document for extraction.
        /// </summary>
        public static string DocumentExtraction_Document_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Document_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string DocumentExtraction_Document_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_Document_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Contents.
        /// </summary>
        public static string DocumentExtraction_Results_Description {
            get {
                return ResourceManager.GetString("DocumentExtraction_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string DocumentExtraction_Results_DisplayName {
            get {
                return ResourceManager.GetString("DocumentExtraction_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract values from text with a model.
        /// </summary>
        public static string ExtractValues_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Values.
        /// </summary>
        public static string ExtractValues_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model group to use.
        /// </summary>
        public static string ExtractValues_ModelGroup_Description {
            get {
                return ResourceManager.GetString("ExtractValues_ModelGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group.
        /// </summary>
        public static string ExtractValues_ModelGroup_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_ModelGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extraction results.
        /// </summary>
        public static string ExtractValues_Results_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string ExtractValues_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text to get extractions from.
        /// </summary>
        public static string ExtractValues_Text_Description {
            get {
                return ResourceManager.GetString("ExtractValues_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ExtractValues_Text_DisplayName {
            get {
                return ResourceManager.GetString("ExtractValues_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates submission result file for a given submission..
        /// </summary>
        public static string GenerateSubmissionResult_Description {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Submission Result.
        /// </summary>
        public static string GenerateSubmissionResult_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the generated file.
        /// </summary>
        public static string GenerateSubmissionResult_Result_Description {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string GenerateSubmissionResult_Result_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of the submission to generate the file for..
        /// </summary>
        public static string GenerateSubmissionResult_SubmissionID_Description {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_SubmissionID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionID.
        /// </summary>
        public static string GenerateSubmissionResult_SubmissionID_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSubmissionResult_SubmissionID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico credentials scope.
        /// </summary>
        public static string IndicoIPA_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico IPA.
        /// </summary>
        public static string IndicoIPA_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Host Address.
        /// </summary>
        public static string IndicoIPA_Host_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host.
        /// </summary>
        public static string IndicoIPA_Host_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Token.
        /// </summary>
        public static string IndicoIPA_Token_Description {
            get {
                return ResourceManager.GetString("IndicoIPA_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string IndicoIPA_Token_DisplayName {
            get {
                return ResourceManager.GetString("IndicoIPA_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Scope.
        /// </summary>
        public static string IndicoScope_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Scope.
        /// </summary>
        public static string IndicoScope_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico host url (e.g. https://app.indico.io ).
        /// </summary>
        public static string IndicoScope_Host_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string IndicoScope_Host_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indico token.
        /// </summary>
        public static string IndicoScope_Token_Description {
            get {
                return ResourceManager.GetString("IndicoScope_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string IndicoScope_Token_DisplayName {
            get {
                return ResourceManager.GetString("IndicoScope_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of datasets.
        /// </summary>
        public static string ListDatasets_Datasets_Description {
            get {
                return ResourceManager.GetString("ListDatasets_Datasets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasets.
        /// </summary>
        public static string ListDatasets_Datasets_DisplayName {
            get {
                return ResourceManager.GetString("ListDatasets_Datasets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List your datasets.
        /// </summary>
        public static string ListDatasets_Description {
            get {
                return ResourceManager.GetString("ListDatasets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Datasets.
        /// </summary>
        public static string ListDatasets_DisplayName {
            get {
                return ResourceManager.GetString("ListDatasets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a list of submission ids.
        /// </summary>
        public static string ListSubmissions_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Submissions.
        /// </summary>
        public static string ListSubmissions_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission name of input file.
        /// </summary>
        public static string ListSubmissions_InputFilename_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_InputFilename_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input filename.
        /// </summary>
        public static string ListSubmissions_InputFilename_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_InputFilename_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limits the number of submission ids returned.
        /// </summary>
        public static string ListSubmissions_Limit_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_Limit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string ListSubmissions_Limit_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_Limit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is submission retrieved.
        /// </summary>
        public static string ListSubmissions_Retrieved_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_Retrieved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved.
        /// </summary>
        public static string ListSubmissions_Retrieved_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_Retrieved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the specific status of the submission.
        /// </summary>
        public static string ListSubmissions_Status_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ListSubmissions_Status_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of submission ids.
        /// </summary>
        public static string ListSubmissions_SubmissionIDs_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_SubmissionIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionIDs.
        /// </summary>
        public static string ListSubmissions_SubmissionIDs_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_SubmissionIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns submission list.
        /// </summary>
        public static string ListSubmissions_Submissions_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_Submissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string ListSubmissions_Submissions_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_Submissions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of workflow ids to filter output.
        /// </summary>
        public static string ListSubmissions_WorkflowIDs_Description {
            get {
                return ResourceManager.GetString("ListSubmissions_WorkflowIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowIDs.
        /// </summary>
        public static string ListSubmissions_WorkflowIDs_DisplayName {
            get {
                return ResourceManager.GetString("ListSubmissions_WorkflowIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ListWithTimeout_Description {
            get {
                return ResourceManager.GetString("ListWithTimeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListWithTimeout.
        /// </summary>
        public static string ListWithTimeout_DisplayName {
            get {
                return ResourceManager.GetString("ListWithTimeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string ListWithTimeout_One_Description {
            get {
                return ResourceManager.GetString("ListWithTimeout_One_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string ListWithTimeout_One_DisplayName {
            get {
                return ResourceManager.GetString("ListWithTimeout_One_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of dataset to query.
        /// </summary>
        public static string ListWorkflows_DatasetID_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_DatasetID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatasetID.
        /// </summary>
        public static string ListWorkflows_DatasetID_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_DatasetID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List workflows for a dataset.
        /// </summary>
        public static string ListWorkflows_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Workflows.
        /// </summary>
        public static string ListWorkflows_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of workflows.
        /// </summary>
        public static string ListWorkflows_Workflows_Description {
            get {
                return ResourceManager.GetString("ListWorkflows_Workflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string ListWorkflows_Workflows_DisplayName {
            get {
                return ResourceManager.GetString("ListWorkflows_Workflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.OCR.
        /// </summary>
        public static string OCRCategory {
            get {
                return ResourceManager.GetString("OCRCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Preparation.
        /// </summary>
        public static string PreparationCategory {
            get {
                return ResourceManager.GetString("PreparationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.
        /// </summary>
        public static string RootCategory {
            get {
                return ResourceManager.GetString("RootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Submission.
        /// </summary>
        public static string SubmissionCategory {
            get {
                return ResourceManager.GetString("SubmissionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checks the particular submission status for submission.
        /// </summary>
        public static string SubmissionResult_CheckStatus_Description {
            get {
                return ResourceManager.GetString("SubmissionResult_CheckStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckStatus.
        /// </summary>
        public static string SubmissionResult_CheckStatus_DisplayName {
            get {
                return ResourceManager.GetString("SubmissionResult_CheckStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetches json result for a submission.
        /// </summary>
        public static string SubmissionResult_Description {
            get {
                return ResourceManager.GetString("SubmissionResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Result.
        /// </summary>
        public static string SubmissionResult_DisplayName {
            get {
                return ResourceManager.GetString("SubmissionResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result of the submission.
        /// </summary>
        public static string SubmissionResult_Result_Description {
            get {
                return ResourceManager.GetString("SubmissionResult_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string SubmissionResult_Result_DisplayName {
            get {
                return ResourceManager.GetString("SubmissionResult_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id of the submission.
        /// </summary>
        public static string SubmissionResult_SubmissionID_Description {
            get {
                return ResourceManager.GetString("SubmissionResult_SubmissionID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionID.
        /// </summary>
        public static string SubmissionResult_SubmissionID_DisplayName {
            get {
                return ResourceManager.GetString("SubmissionResult_SubmissionID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changes to make to raw predictions.
        /// </summary>
        public static string SubmitReview_Changes_Description {
            get {
                return ResourceManager.GetString("SubmitReview_Changes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string SubmitReview_Changes_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_Changes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an &quot;Auto&quot; Review for a submission. Requires that the submission be in PENDING_AUTO_REVIEW status..
        /// </summary>
        public static string SubmitReview_Description {
            get {
                return ResourceManager.GetString("SubmitReview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string SubmitReview_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have this submission bypass the Review queue(or exceptions queue if &lt;Rejected&gt; is True) and mark as Complete. *NOT RECOMMENDED*.
        /// </summary>
        public static string SubmitReview_ForceComplete_Description {
            get {
                return ResourceManager.GetString("SubmitReview_ForceComplete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceComplete.
        /// </summary>
        public static string SubmitReview_ForceComplete_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_ForceComplete_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reject the predictions and place the submissionin the review queue. Must be true if Changes not provided.
        /// </summary>
        public static string SubmitReview_Rejected_Description {
            get {
                return ResourceManager.GetString("SubmitReview_Rejected_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string SubmitReview_Rejected_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_Rejected_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON response.
        /// </summary>
        public static string SubmitReview_Result_Description {
            get {
                return ResourceManager.GetString("SubmitReview_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string SubmitReview_Result_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of submission to submit reviewEnabled for.
        /// </summary>
        public static string SubmitReview_SubmissionID_Description {
            get {
                return ResourceManager.GetString("SubmitReview_SubmissionID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionID.
        /// </summary>
        public static string SubmitReview_SubmissionID_DisplayName {
            get {
                return ResourceManager.GetString("SubmitReview_SubmissionID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Workflow.
        /// </summary>
        public static string WorkflowCategory {
            get {
                return ResourceManager.GetString("WorkflowCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit files or urls to workflow.
        /// </summary>
        public static string WorkflowSubmission_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Submission.
        /// </summary>
        public static string WorkflowSubmission_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths of files to submit.
        /// </summary>
        public static string WorkflowSubmission_FilePaths_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_FilePaths_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePaths.
        /// </summary>
        public static string WorkflowSubmission_FilePaths_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_FilePaths_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of submission ids.
        /// </summary>
        public static string WorkflowSubmission_SubmissionIDs_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_SubmissionIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionIDs.
        /// </summary>
        public static string WorkflowSubmission_SubmissionIDs_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_SubmissionIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls to submit.
        /// </summary>
        public static string WorkflowSubmission_Urls_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Urls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        public static string WorkflowSubmission_Urls_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_Urls_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of workflow for submission.
        /// </summary>
        public static string WorkflowSubmission_WorkflowID_Description {
            get {
                return ResourceManager.GetString("WorkflowSubmission_WorkflowID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowID.
        /// </summary>
        public static string WorkflowSubmission_WorkflowID_DisplayName {
            get {
                return ResourceManager.GetString("WorkflowSubmission_WorkflowID_DisplayName", resourceCulture);
            }
        }
    }
}
